name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies npm
        run: npm install
        
      - name: Install dependencies
        run: npm ci
        
      - name: Install eslint-config-prettier
        run: npm install eslint-config-prettier@8.3.0
        
      - name: Lint code
        run: npm run lint
