name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Lint with ESLint
        run: npm run lint

      - name: Check for formatting errors with Prettier
        run: npx prettier --check .

      - name: Check for formatting errors with ESLint
        run: npx eslint --fix --no-ignore .

      - name: Check for formatting errors with stylelint
        run: npx stylelint '**/*.{css,scss}'
